//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/MenuController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuController"",
    ""maps"": [
        {
            ""name"": ""MenuAction"",
            ""id"": ""02561cdb-f800-46b8-9149-6f565801abed"",
            ""actions"": [
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""437f4abc-ab84-406e-b176-8bb4798da06d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""28da241d-5e79-4266-ade0-42037c17c3cf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MenuAction
        m_MenuAction = asset.FindActionMap("MenuAction", throwIfNotFound: true);
        m_MenuAction_PauseGame = m_MenuAction.FindAction("PauseGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MenuAction
    private readonly InputActionMap m_MenuAction;
    private IMenuActionActions m_MenuActionActionsCallbackInterface;
    private readonly InputAction m_MenuAction_PauseGame;
    public struct MenuActionActions
    {
        private @MenuController m_Wrapper;
        public MenuActionActions(@MenuController wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseGame => m_Wrapper.m_MenuAction_PauseGame;
        public InputActionMap Get() { return m_Wrapper.m_MenuAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActionActions set) { return set.Get(); }
        public void SetCallbacks(IMenuActionActions instance)
        {
            if (m_Wrapper.m_MenuActionActionsCallbackInterface != null)
            {
                @PauseGame.started -= m_Wrapper.m_MenuActionActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_MenuActionActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_MenuActionActionsCallbackInterface.OnPauseGame;
            }
            m_Wrapper.m_MenuActionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
            }
        }
    }
    public MenuActionActions @MenuAction => new MenuActionActions(this);
    public interface IMenuActionActions
    {
        void OnPauseGame(InputAction.CallbackContext context);
    }
}
